# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: index
  unique: true

- name: blog_index
  unique: true
  elements: [article]

- name: blog_page
  elements: [blog_page_content]
  autogenerate: [blog_page_content]
